In [6]:
import pandas as pd
import numpy as np

In [7]:
pd.set_option("display.max_columns", None)
data=pd.read_csv('raw_data.csv')
data

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253676,0.0,1.0,1.0,1.0,18.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253677,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,0.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
253679,1.0,1.0,1.0,1.0,25.0,0.0,0.0,2.0,1.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [8]:
data.keys()

Index(['HeartDiseaseorAttack', 'HighBP', 'HighChol', 'CholCheck', 'BMI',
       'Smoker', 'Stroke', 'Diabetes', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education',
       'Income'],
      dtype='str')

In [9]:
data.isnull().sum()

HeartDiseaseorAttack    0
HighBP                  0
HighChol                0
CholCheck               0
BMI                     0
Smoker                  0
Stroke                  0
Diabetes                0
PhysActivity            0
Fruits                  0
Veggies                 0
HvyAlcoholConsump       0
AnyHealthcare           0
NoDocbcCost             0
GenHlth                 0
MentHlth                0
PhysHlth                0
DiffWalk                0
Sex                     0
Age                     0
Education               0
Income                  0
dtype: int64

In [10]:
data.duplicated().sum()

np.int64(23899)

In [11]:
data.shape

(253680, 22)

In [12]:
data=data.drop_duplicates()

In [13]:
data.shape

(229781, 22)

In [14]:
data.dtypes

HeartDiseaseorAttack    float64
HighBP                  float64
HighChol                float64
CholCheck               float64
BMI                     float64
Smoker                  float64
Stroke                  float64
Diabetes                float64
PhysActivity            float64
Fruits                  float64
Veggies                 float64
HvyAlcoholConsump       float64
AnyHealthcare           float64
NoDocbcCost             float64
GenHlth                 float64
MentHlth                float64
PhysHlth                float64
DiffWalk                float64
Sex                     float64
Age                     float64
Education               float64
Income                  float64
dtype: object

In [15]:
numerical_cols = data.select_dtypes(include=[np.number]).columns

for col in numerical_cols:
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = data[(data[col] < lower_bound) | (data[col] > upper_bound)]
    
    print(f"Column '{col}' has {len(outliers)} outliers.")

for i in ['BMI', 'MentHlth', 'PhysHlth']:
    print(f"{i},mini={min(data[i])},maxi={max(data[i])}")

Column 'HeartDiseaseorAttack' has 23717 outliers.
Column 'HighBP' has 0 outliers.
Column 'HighChol' has 0 outliers.
Column 'CholCheck' has 9298 outliers.
Column 'BMI' has 5638 outliers.
Column 'Smoker' has 0 outliers.
Column 'Stroke' has 10284 outliers.
Column 'Diabetes' has 39726 outliers.
Column 'PhysActivity' has 0 outliers.
Column 'Fruits' has 0 outliers.
Column 'Veggies' has 47148 outliers.
Column 'HvyAlcoholConsump' has 13950 outliers.
Column 'AnyHealthcare' has 12391 outliers.
Column 'NoDocbcCost' has 21326 outliers.
Column 'GenHlth' has 12078 outliers.
Column 'MentHlth' has 36163 outliers.
Column 'PhysHlth' has 34347 outliers.
Column 'DiffWalk' has 42626 outliers.
Column 'Sex' has 0 outliers.
Column 'Age' has 0 outliers.
Column 'Education' has 0 outliers.
Column 'Income' has 0 outliers.
BMI,mini=12.0,maxi=98.0
MentHlth,mini=0.0,maxi=30.0
PhysHlth,mini=0.0,maxi=30.0

In [16]:
for i in ['BMI','MentHlth','PhysHlth','Age']:
    print(f"{i}Mean: {data[i].mean()}")
    print(f"{i}Std Dev: {data[i].std()}")

BMIMean: 28.685670268647105
BMIStd Dev: 6.7863603415278595
MentHlthMean: 3.5053725068652324
MentHlthStd Dev: 7.71372491057319
PhysHlthMean: 4.67517766917195
PhysHlthStd Dev: 9.046567640200625
AgeMean: 8.086582441542165
AgeStd Dev: 3.0938088288659333

In [17]:
data.head()

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

In [18]:
y=data.iloc[:,0]
x=data.iloc[:,1:]
x

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253676,1.0,1.0,1.0,18.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253677,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
253679,1.0,1.0,1.0,25.0,0.0,0.0,2.0,1.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [19]:
data.to_csv("processed_data.csv")

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [21]:
pd.set_option("display.max_columns", None)
print(x_test)

        HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  Diabetes  \
175726     0.0       1.0        1.0  33.0     1.0     0.0       0.0
227694     0.0       0.0        1.0  27.0     1.0     0.0       0.0
85626      1.0       0.0        1.0  20.0     0.0     0.0       0.0
141915     1.0       0.0        1.0  28.0     1.0     0.0       0.0
93630      0.0       0.0        1.0  15.0     1.0     0.0       0.0
...        ...       ...        ...   ...     ...     ...       ...
182539     0.0       1.0        1.0  22.0     1.0     0.0       0.0
215051     0.0       1.0        1.0  25.0     0.0     0.0       0.0
34784      1.0       1.0        1.0  21.0     1.0     0.0       0.0
203968     1.0       1.0        1.0  27.0     0.0     0.0       0.0
166115     1.0       1.0        1.0  34.0     1.0     0.0       2.0

        PhysActivity  Fruits  Veggies  HvyAlcoholConsump  AnyHealthcare  \
175726           1.0     0.0      0.0                0.0            1.0
227694           0.0     0.0      1.0                1.0            1.0
85626            1.0     1.0      1.0                0.0            1.0
141915           1.0     1.0      1.0                0.0            1.0
93630            0.0     0.0      1.0                0.0            1.0
...              ...     ...      ...                ...            ...
182539           1.0     1.0      1.0                0.0            1.0
215051           1.0     1.0      1.0                0.0            1.0
34784            0.0     1.0      0.0                0.0            1.0
203968           0.0     0.0      0.0                0.0            1.0
166115           0.0     0.0      0.0                0.0            1.0

        NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  \
175726          1.0      3.0      20.0      21.0       1.0  0.0  12.0
227694          0.0      5.0      30.0      30.0       0.0  0.0   4.0
85626           0.0      2.0       0.0       0.0       0.0  0.0  11.0
141915          0.0      2.0       0.0       0.0       0.0  0.0  13.0
93630           0.0      5.0      30.0      30.0       1.0  0.0   6.0
...             ...      ...       ...       ...       ...  ...   ...
182539          0.0      1.0       0.0       0.0       0.0  0.0   8.0
215051          0.0      3.0       0.0       1.0       0.0  1.0   8.0
34784           0.0      4.0      20.0       7.0       1.0  0.0   5.0
203968          0.0      3.0       2.0       5.0       1.0  0.0   7.0
166115          0.0      4.0       0.0      15.0       1.0  1.0   7.0

        Education  Income
175726        3.0     2.0
227694        4.0     1.0
85626         6.0     5.0
141915        5.0     4.0
93630         4.0     8.0
...           ...     ...
182539        4.0     7.0
215051        5.0     8.0
34784         5.0     6.0
203968        5.0     8.0
166115        5.0     5.0

[45957 rows x 21 columns]

In [28]:
import joblib
from sklearn.preprocessing import StandardScaler
cols_to_scale=['BMI', 'MentHlth', 'PhysHlth', 'Age']
sc=StandardScaler()
x_train[cols_to_scale] = sc.fit_transform(x_train[cols_to_scale])
x_test[cols_to_scale] = sc.transform(x_test[cols_to_scale])
joblib.dump(sc,"../saved_models/scaler.joblib")

['../saved_models/scaler.joblib']

In [29]:
import tensorflow as tf
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, recall_score

In [30]:
#Logistic Regression
log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [31]:
#Decision tree
tree_clf=DecisionTreeClassifier(max_depth=7,random_state=42)
tree_clf.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=7, random_state=42)

In [32]:
#ANN
ann=tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=32,activation='relu'))
ann.add(tf.keras.layers.Dense(units=16,activation='relu'))
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
early_stopping=tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True)
reduce_lr=tf.keras.callbacks.ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.2,
    patience=10,
    min_lr=0.0001)
ann.fit(x_train,y_train,batch_size=32,epochs=50,validation_data=(x_test,y_test))

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step - accuracy: 0.8945 - loss: 0.2719 - val_accuracy: 0.9008 - val_loss: 0.2579
Epoch 2/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - accuracy: 0.8987 - loss: 0.2612 - val_accuracy: 0.9008 - val_loss: 0.2562
Epoch 3/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 20s 2ms/step - accuracy: 0.8986 - loss: 0.2596 - val_accuracy: 0.9008 - val_loss: 0.2556
Epoch 4/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 20s 2ms/step - accuracy: 0.8985 - loss: 0.2589 - val_accuracy: 0.9006 - val_loss: 0.2575
Epoch 5/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - accuracy: 0.8991 - loss: 0.2585 - val_accuracy: 0.8996 - val_loss: 0.2605
Epoch 6/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 20s 2ms/step - accuracy: 0.8989 - loss: 0.2581 - val_accuracy: 0.9009 - val_loss: 0.2551
Epoch 7/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - accuracy: 0.8990 - loss: 0.2577 - val_accuracy: 0.9009 - val_loss: 0.2568
Epoch 8/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - accuracy: 0.8989 - loss: 0.2577 - val_accuracy: 0.9011 - val_loss: 0.2544
Epoch 9/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 20s 2ms/step - accuracy: 0.8988 - loss: 0.2574 - val_accuracy: 0.9010 - val_loss: 0.2550
Epoch 10/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - accuracy: 0.8991 - loss: 0.2572 - val_accuracy: 0.9006 - val_loss: 0.2548
Epoch 11/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - accuracy: 0.8990 - loss: 0.2570 - val_accuracy: 0.9008 - val_loss: 0.2544
Epoch 12/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step - accuracy: 0.8990 - loss: 0.2570 - val_accuracy: 0.9011 - val_loss: 0.2548
Epoch 13/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step - accuracy: 0.8988 - loss: 0.2568 - val_accuracy: 0.9007 - val_loss: 0.2560
Epoch 14/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - accuracy: 0.8990 - loss: 0.2566 - val_accuracy: 0.9010 - val_loss: 0.2548
Epoch 15/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step - accuracy: 0.8991 - loss: 0.2565 - val_accuracy: 0.8998 - val_loss: 0.2566
Epoch 16/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step - accuracy: 0.8988 - loss: 0.2565 - val_accuracy: 0.9011 - val_loss: 0.2560
Epoch 17/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - accuracy: 0.8992 - loss: 0.2563 - val_accuracy: 0.9007 - val_loss: 0.2555
Epoch 18/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 16s 3ms/step - accuracy: 0.8990 - loss: 0.2563 - val_accuracy: 0.9005 - val_loss: 0.2563
Epoch 19/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 19s 2ms/step - accuracy: 0.8991 - loss: 0.2563 - val_accuracy: 0.9008 - val_loss: 0.2554
Epoch 20/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step - accuracy: 0.8994 - loss: 0.2561 - val_accuracy: 0.9010 - val_loss: 0.2548
Epoch 21/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 18s 2ms/step - accuracy: 0.8993 - loss: 0.2559 - val_accuracy: 0.9005 - val_loss: 0.2563
Epoch 22/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 20s 2ms/step - accuracy: 0.8993 - loss: 0.2559 - val_accuracy: 0.8999 - val_loss: 0.2562
Epoch 23/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step - accuracy: 0.8991 - loss: 0.2559 - val_accuracy: 0.9008 - val_loss: 0.2543
Epoch 24/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 18s 2ms/step - accuracy: 0.8996 - loss: 0.2558 - val_accuracy: 0.9008 - val_loss: 0.2551
Epoch 25/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 20s 2ms/step - accuracy: 0.8991 - loss: 0.2558 - val_accuracy: 0.9007 - val_loss: 0.2549
Epoch 26/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - accuracy: 0.8993 - loss: 0.2555 - val_accuracy: 0.9009 - val_loss: 0.2549
Epoch 27/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - accuracy: 0.8995 - loss: 0.2555 - val_accuracy: 0.9011 - val_loss: 0.2545
Epoch 28/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - accuracy: 0.8997 - loss: 0.2555 - val_accuracy: 0.9008 - val_loss: 0.2559
Epoch 29/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 20s 2ms/step - accuracy: 0.8993 - loss: 0.2556 - val_accuracy: 0.9008 - val_loss: 0.2545
Epoch 30/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - accuracy: 0.8995 - loss: 0.2555 - val_accuracy: 0.9011 - val_loss: 0.2547
Epoch 31/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - accuracy: 0.8996 - loss: 0.2553 - val_accuracy: 0.9013 - val_loss: 0.2550
Epoch 32/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - accuracy: 0.8998 - loss: 0.2553 - val_accuracy: 0.9010 - val_loss: 0.2555
Epoch 33/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 20s 2ms/step - accuracy: 0.8995 - loss: 0.2552 - val_accuracy: 0.9006 - val_loss: 0.2553
Epoch 34/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 23s 3ms/step - accuracy: 0.8993 - loss: 0.2550 - val_accuracy: 0.9009 - val_loss: 0.2558
Epoch 35/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 17s 2ms/step - accuracy: 0.8995 - loss: 0.2552 - val_accuracy: 0.9010 - val_loss: 0.2549
Epoch 36/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 22s 2ms/step - accuracy: 0.8995 - loss: 0.2550 - val_accuracy: 0.9006 - val_loss: 0.2570
Epoch 37/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 20s 2ms/step - accuracy: 0.8996 - loss: 0.2549 - val_accuracy: 0.9009 - val_loss: 0.2561
Epoch 38/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - accuracy: 0.8997 - loss: 0.2550 - val_accuracy: 0.9004 - val_loss: 0.2550
Epoch 39/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 19s 2ms/step - accuracy: 0.8993 - loss: 0.2550 - val_accuracy: 0.9010 - val_loss: 0.2554
Epoch 40/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - accuracy: 0.8996 - loss: 0.2548 - val_accuracy: 0.9006 - val_loss: 0.2551
Epoch 41/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - accuracy: 0.8995 - loss: 0.2549 - val_accuracy: 0.9010 - val_loss: 0.2558
Epoch 42/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 20s 2ms/step - accuracy: 0.8995 - loss: 0.2547 - val_accuracy: 0.9010 - val_loss: 0.2573
Epoch 43/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - accuracy: 0.8994 - loss: 0.2548 - val_accuracy: 0.9007 - val_loss: 0.2566
Epoch 44/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step - accuracy: 0.8996 - loss: 0.2547 - val_accuracy: 0.9004 - val_loss: 0.2551
Epoch 45/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 18s 2ms/step - accuracy: 0.8994 - loss: 0.2547 - val_accuracy: 0.9005 - val_loss: 0.2566
Epoch 46/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 21s 2ms/step - accuracy: 0.8996 - loss: 0.2546 - val_accuracy: 0.9004 - val_loss: 0.2553
Epoch 47/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 16s 3ms/step - accuracy: 0.8998 - loss: 0.2546 - val_accuracy: 0.9006 - val_loss: 0.2555
Epoch 48/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 17s 2ms/step - accuracy: 0.8993 - loss: 0.2545 - val_accuracy: 0.8999 - val_loss: 0.2562
Epoch 49/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 24s 3ms/step - accuracy: 0.8998 - loss: 0.2544 - val_accuracy: 0.9007 - val_loss: 0.2556
Epoch 50/50
5745/5745 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step - accuracy: 0.8997 - loss: 0.2544 - val_accuracy: 0.9006 - val_loss: 0.2562

In [33]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
models=[("Logistic Regression", log_reg), ("Decision Tree", tree_clf),("ANN",ann)]
for name,model  in models:
    y_pred=model.predict(x_test)
    if name=="ANN":
        y_pred=(y_pred)>0.5
    print(f"\n{name}")
    cm=confusion_matrix(y_test,y_pred)
    acc=accuracy_score(y_test,y_pred)
    cr=classification_report(y_test,y_pred)
    print(f'Confusion Matrix\n{cm}\nAccuracy:{acc}\nClassification Report\n{cr}')

Logistic Regression
Confusion Matrix
[[40803   466]
 [ 4113   575]]
Accuracy:0.9003633831625215
Classification Report
              precision    recall  f1-score   support

         0.0       0.91      0.99      0.95     41269
         1.0       0.55      0.12      0.20      4688

    accuracy                           0.90     45957
   macro avg       0.73      0.56      0.57     45957
weighted avg       0.87      0.90      0.87     45957


Decision Tree
Confusion Matrix
[[40959   310]
 [ 4282   406]]
Accuracy:0.9000805100419957
Classification Report
              precision    recall  f1-score   support

         0.0       0.91      0.99      0.95     41269
         1.0       0.57      0.09      0.15      4688

    accuracy                           0.90     45957
   macro avg       0.74      0.54      0.55     45957
weighted avg       0.87      0.90      0.87     45957

1437/1437 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step

ANN
Confusion Matrix
[[40882   387]
 [ 4182   506]]
Accuracy:0.9005809778706182
Classification Report
              precision    recall  f1-score   support

         0.0       0.91      0.99      0.95     41269
         1.0       0.57      0.11      0.18      4688

    accuracy                           0.90     45957
   macro avg       0.74      0.55      0.56     45957
weighted avg       0.87      0.90      0.87     45957

In [34]:
x_test.to_csv("test_data.csv")
y_test.to_csv("test_result.csv")

In [35]:
#Save models
joblib.dump(log_reg,"../saved_models/log_reg.joblib")
joblib.dump(tree_clf,"../saved_models/tree_clf.joblib")
ann.save("../saved_models/ann.keras")